build:
  image: default-bionic
  environment:
    php:
      version: 8.3.3
      ini:
        xdebug.mode: coverage
  nodes:
    analysis:
      dependencies:
        before:
          - 'sudo git clone https://github.com/grommunio/mapi-header-php.git /usr/share/php-mapi'
      project_setup:
        override:
          - true
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
            use_website_config: true
    tests:
      dependencies:
        before:
          - 'sudo git clone https://github.com/grommunio/mapi-header-php.git /usr/share/php-mapi'
filter:
  excluded_paths:
    - "vendor"
    - "*/vendor/*"
checks:
  php:
    code_rating: true
    duplication: true
    excluded_dependencies:
      - phpunit/phpunit
tools:
    php_cs_fixer:
        config: .php_cs.dist
        rules:
            '@PhpCsFixer': true
            blank_line_before_statement:
                statements:
                    - case
                    - continue
                    - declare
                    - default
                    - exit
                    - goto
                    - phpdoc
                    - return
                    - switch
                    - throw
                    - try
                    - yield
            braces:
                position_after_functions_and_oop_constructs: same
            curly_braces_position:
                functions_opening_brace: same_line
                classes_opening_brace: same_line
            concat_space:
                spacing: one
            control_structure_continuation_position:
                position: next_line
            indentation_type: true
            operator_linebreak:
                position: end
            ordered_class_elements: false
            single_line_comment_style: false
            single_quote: false
            yoda_style:
                equal: false
                identical: false
                less_and_greater: false
coding_style:
  php:
    spaces:
      indent_style: "\t"
      line_endings: "\n"
    braces:
      position_after_functions_and_oop_constructs: "same"
    yoda_conditions: false
    keywords:
      casing: "lower"
    operators:
      concatenate_space: "one"
    control_structures:
      continuation_position: "next_line"
    comments:
      inline_comment_spacing: false
    quotes:
      single_quote: false
